SDK=../SDK
INCLUDES=-I$(SDK)/CHeaders/XPLM -I$(SDK)/CHeaders/Widgets

# all sources without jwctrl_sound*.cpp which gets special treatment
SOURCES=openSAM.cpp os_dgs.cpp samjw.cpp jwctrl.cpp os_ui.cpp os_anim.cpp sam_xml.cpp log_msg.cpp read_wav.cpp \
    plane.cpp myplane.cpp LTAPI.cpp mpadapter.cpp mpadapter_xpilot.cpp mpadapter_tgxp.cpp mpadapter_lt.cpp

# the c++ standard to use
CXXSTD=-std=c++20

OPT=-O3

# e.g. -DNDEBUG
DEBUG=

