#!/bin/bash
set -v
rm -f openSAM.zip
(cd openSAM-pkg && /c/Program\ Files/7-Zip/7z.exe a ../openSAM.zip *)

./sync_xp11_pkg.sh
(cd openSAM-pkg_XP11 && /c/Program\ Files/7-Zip/7z.exe a ../openSAM_XP11.zip *)
