"""
    gen_libjw_fromjw.py: Generate a library jetway .obj from a traditional SAM jw .obj .

    Copyright (C) 2025  Holger Teutsch

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
    USA
"""

VERSION = "1.0.0"

import sys,os, os.path, shutil, logging

log = logging.getLogger("gen_libjw_from_jw")
logging.basicConfig(
    level=logging.INFO,
    handlers=[
        logging.StreamHandler(),
    ],
)

log.info(f"Version: {VERSION}")
log.info(f"args: {sys.argv}")

def usage():
    log.error(
        """
        usage:
            gen_libjw_from_jw
                -jwpath     path of jw obj
                -set        set name, e.g. MyStudio_01

        Example:
            gen_libjw_from_jw -jwpath "E:/X-Plane-12/Custom Scenery/MisterX_Library/Airport/Jetways-SAM/Jetway_Steel_Modern_4m.obj -set MrX_openSAM_1
        """
    )
    sys.exit(2)

jwpath = None
set_name = None

i = 1
while i < len(sys.argv):
    if sys.argv[i] == "-jwpath":
        i = i + 1
        if i >= len(sys.argv):
            usage()
        jwpath = sys.argv[i]
    elif sys.argv[i] == "-set":
        i = i + 1
        if i >= len(sys.argv):
            usage()
        set_name = sys.argv[i]
    else:
            usage()
    i = i + 1

if jwpath is None or set_name is None:
    usage()

def gen_libjw_obj():
    """Generate a library jetway .obj from a traditional SAM jw .obj"""
    ljw_obj_path = os.path.basename(jwpath)
    ljw_obj_path = os.path.splitext(ljw_obj_path)[0] + "_ljw.obj"

    log.info(f"Generating library jetway object from {jwpath} to {ljw_obj_path} ...")

    lines = open(jwpath, 'r').readlines()

    with open(ljw_obj_path, 'w', newline='\n') as ljw_obj_file:
        for line in lines:
            if "sam/jetway/rotate" in line:
                line = line.replace("sam/jetway/rotate", f"sam/jetway/{set_name}/rotate")
            elif "sam/jetway/extent" in line:
                line = line.replace("sam/jetway/extent", f"sam/jetway/{set_name}/extent")
            elif "sam/jetway/wheel" in line:
                line = line.replace("sam/jetway/wheel", f"sam/jetway/{set_name}/wheel")
            elif "sam/jetway/warnlight" in line:
                line = line.replace("sam/jetway/warnlight", f"sam/jetway/{set_name}/warnlight")

            ljw_obj_file.write(line)

        ljw_obj_file.write(f"\n# Generated by gen_libjw_from_jw.py version {VERSION} from {jwpath}\n")

    log.info(f"Library jetway object generated: {ljw_obj_path}")

################################################################################

gen_libjw_obj()

log.info("Done.")
